### ISSUE TITLE
Segmentation fault when negative values is set to terminal size

### ISSUE THREAD

**Issue by sonulohani** [christianparpart/contour#188]
## Description

Set negative values to contour.yml 

```yml
# Determines the initial terminal sice in characters.
  terminal_size:
    columns: -130
      lines: 30
```

and see the crash.
